# Generated by Django 4.2.5 on 2025-05-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_product_images_productimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_top_selling',
            field=models.BooleanField(default=False),
        ),
    ]
