# Generated by Django 4.2.5 on 2025-08-01 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('u_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_offer', models.BooleanField(default=False)),
                ('is_top_selling', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
